GRANT USAGE ON SCHEMA public to foo;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO foo;

-- repeat code below for each database:

GRANT CONNECT ON DATABASE foo to bar;

GRANT USAGE ON SCHEMA public to foo; 
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO foo;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO foo;